version: '3.8'

services:
  ollama:
    build: 
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - /home/ec2-user/.ollama:/root/.ollama  # Mount existing models to avoid re-download
    environment:
      - OLLAMA_HOST=0.0.0.0

  fastapi:
    build: .
    container_name: fastapi
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434  # FastAPI will talk to Ollama using this URL